"use client";

import { PrivyProvider } from "@privy-io/react-auth";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Since we're using privy for auth inside layout.tsx, we need to remove the meta data

// export const metadata: Metadata = {
//   title: "Hash-Hive",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/Logo.svg"
//   }
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrivyProvider
          appId="cm79x97db06al11zszxuklw7w"
          config={{
            // Customize Privy's appearance in your app
            appearance: {
              theme: "dark",
              accentColor: "#676FFF",
              logo: "https://your-logo-url",
            },
            // Create embedded wallets for users who don't have a wallet
            embeddedWallets: {
              createOnLogin: "users-without-wallets",
            },
          }}
        >
          {/* Navbar */}
          <Navbar />
          {children}
        </PrivyProvider>
      </body>
    </html>
  );
}